### ISSUE TITLE
Before reboot annotations not for master nodes

### ISSUE THREAD

**Issue by hacor** [coreos/container-linux-update-operator#173]
Hello,

I use CLUO with success on a Tectonic Vanilla K8s cluster (1.8.4).
The worker nodes reboot perfectly using the `locksmithctl send-need-reboot` command, but the master nodes get stuck because they wait for the set `before-reboot` annotation. The tolerations in the daemonset yaml say to avoid master nodes, but this way they never get annotated. 

Standard the master nodes are unschedulable.
Do I need to run another Daemonset made for the master nodes, which automatically sets the annotation? This breaks with the unschedulable logic.

Any suggestions would be appreciated!

Best regards,

Hacor

The used before-reboot-annotations in the operator yaml:
```
- "--before-reboot-annotations"
- "ceph-reboot-check"
```

The yaml of the before-reboot-annotation:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-reboot-check
  namespace: rook
spec:
  template:
    metadata:
      labels:
        app: ceph-reboot-check
    spec:
      serviceAccountName: rook-node-annotator
      nodeSelector:
        container-linux-update.v1.coreos.com/before-reboot: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: ceph-reboot-check
        image: rook/toolbox:master
        imagePullPolicy: IfNotPresent
        command: ["/scripts/status-check.sh"]
        env:
          - name: ROOK_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: rook-ceph-mon
                key: admin-secret
          - name: NODE_NAME
            valueFrom:
               fieldRef:
                  fieldPath: spec.nodeName
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /dev
            name: dev
          - mountPath: /sys/bus
            name: sysbus
          - mountPath: /lib/modules
            name: libmodules
          - name: mon-endpoint-volume
            mountPath: /etc/rook
          - name: status-script
            mountPath: /scripts
      hostNetwork: false
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: status-script
          configMap:
            name: ceph-reboot-check-script
            defaultMode: 0740
```

**Comment by dghubble** [comment]
I'm not sure I understand your problem. Typically, if you set required `--before-reboot-annotations`, your custom DaemonSet that does custom work and sets the annotation once done would tolerate running on master nodes.

It looks like you're already tolerating `node-role.kubernetes.io/master`. Scheduleable/Unschedulable should not apply to DaemonSets.

**Comment by hacor** [comment]
Thanks for your reply!

> It looks like you're already tolerating node-role.kubernetes.io/master. Scheduleable/Unschedulable should not apply to DaemonSets. 

I didn't know that thanks!

Then there must be another reason why the controller node didn't want to reboot and the workers did.
I will look into this some more! I will keep you posted!

Beste regards

**Comment by hacor** [comment]
I was just able to test again on a fresh system and the controller rebooted just fine.
I'm sorry to have troubled you. One thing I still don't quite get is the `tolerations`, the daemonset contains 
```
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```
So I thought this meant it doens't run on the masters? (`effect: NoSchedule`)
